version: 2
jobs:
  build:
    docker:
      - image: node:8
    branches:
        only:
          - master
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm i npm@latest -g
            npm install
      - deploy:
          name: Push to expo.io
          command: |
            ./node_modules/.bin/exp login -u ${EXPO_ACCOUNT} -p ${EXPO_PASSWORD}
            openssl aes-256-cbc -k $DECRYPT_KEY -d -in .circleci/env-staging.json.encrypted -out env-staging.json
            openssl aes-256-cbc -k $DECRYPT_KEY -d -in .circleci/env-prod.json.encrypted -out env-prod.json
            ./node_modules/.bin/exp publish --release-channel prod
