version: 2
jobs:
  build:
    docker:
      - image: node:8
    # branches:
      # only:
      #   - master
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - deploy:
          name: Push to expo.io
          command: |
            ./node_modules/.bin/exp login -u ${EXPO_ACCOUNT} -p ${EXPO_PASSWORD}
            openssl aes-256-cbc -k $DECRYPT_KEY -d -in .circleci/env-prod.json.encrepted -out env-prod.json
            ./node_modules/.bin/exp publish --release-channel prod
